services:

  app:
    image: l4rm4nd/requestbin:latest
    hostname: requestbin
    container_name: requestbin
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
        REALM: prod
        REDIS_URL: "redis://:SecretPassword@redis:6379"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.50
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL        
    links:
      - redis
    #networks:
    #  - dev
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=dev
    #  - traefik.http.routers.requestbin.rule=Host(`bin.example.com`)
    #  - traefik.http.services.requestbin.loadbalancer.server.port=8000
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.requestbin.middlewares=local-ipwhitelist@file,authelia@docker
    
  redis:
    image: redis:8-alpine
    hostname: redis
    container_name: requestbin_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "SecretPassword"]
    #networks:
    #  - dev

#networks:
#  dev:
#    external: true
