version: "2"

#networks:
#  isolated-npm-bridge:
#    external: true

services:
  app:
    #networks:
    #  - isolated-npm-bridge
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    build: .
    hostname: requestbin
    container_name: requestbin
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
        - redis

  redis:
    image: redis
    #networks:
    #  - isolated-npm-bridge
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    hostname: redis
    container_name: requestbin_redis
    restart: unless-stopped
