version: "2"

services:
  app:
    #networks:
    #  - dev
    restart: unless-stopped
    expose:
      - 8000
    build: .
    hostname: requestbin
    container_name: requestbin
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
      - redis
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=dev
    #  - traefik.http.routers.requestbin.rule=Host(`bin.example.com`)
    #  - traefik.http.services.requestbin.loadbalancer.server.port=8000
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.requestbin.middlewares=local-ipwhitelist@file,authelia@docker
    
  redis:
    image: redis
    #networks:
    #  - dev
    hostname: redis
    container_name: requestbin_redis
    restart: unless-stopped

#networks:
#  dev:
#    external: true
